name: Run DB Schema

on:
  workflow_dispatch:    # allows manual run from Actions tab

jobs:
  apply-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pip & dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DB schema script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python -m scripts.run_schema

